# Use official Qdrant image
# FROM qdrant/qdrant:v1.8.3

RUN apt-get update && apt-get install -y curl

# # Set non-root user (security best practice)
USER 1001

# # Expose default Qdrant ports
# EXPOSE 6333 6334

# Start Qdrant
# CMD ["./entrypoint.sh"]

